In [3]:
import chardet
import pandas as pd
filename = '소상공인시장진흥공단_상가(상권)정보_경남_202312.csv'
with open(filename,'rb') as f:
    result = chardet.detect(f.readline())
    print(result['encoding'])

utf-8

In [4]:
data = pd.read_csv('소상공인시장진흥공단_상가(상권)정보_경남_202312.csv',
                  encoding='UTF-8')
data

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220805431207,일로딜로,NaN,G2,소매,G209,섬유·의복·신발 소매,G20903,유아용 의류 소매업,G47417,...,4812112900100300001013983,뉴코아아울렛,경상남도 창원시 의창구 창원대로397번길 6,641847,51393,NaN,4,NaN,128.642214,35.234522
1,MA010120220805431535,오미당꽈배기,NaN,I2,음식,I210,기타 간이,I21001,빵/도넛,I56191,...,4825013200108260004000001,NaN,경상남도 김해시 율하6로 56,621340,51020,NaN,1,NaN,128.824132,35.171836
2,MA010120220805432253,하나병원,NaN,Q1,보건의료,Q101,병원,Q10102,일반병원,Q86102,...,4824025024102700001040629,NaN,경상남도 사천시 사천읍 진삼로 1468-8,664805,52518,NaN,NaN,NaN,128.086510,35.082219
3,MA010120220805433603,술마시는심플노래방,NaN,I2,음식,I211,주점,I21104,요리 주점,I56219,...,4822010800100940001007051,동피랑쭈꿀,경상남도 통영시 통영해안로 363-1,650806,53052,NaN,NaN,NaN,128.427303,34.844565
4,MA010120220805433630,남도밥상,NaN,I2,음식,I201,한식,I20101,백반/한정식,I56111,...,4884025021104900008060775,동네방네,경상남도 남해군 남해읍 화전로122번길 25,668803,52414,NaN,NaN,NaN,127.896689,34.842315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166060,MA010120220811190436,라온,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,4884025027104290003000001,NaN,경상남도 남해군 남해읍 망운로 59,668803,52426,NaN,2,NaN,127.887291,34.837908
166061,MA0101202301A0085486,라니,NaN,G2,소매,G209,섬유·의복·신발 소매,G20905,기타 의류 소매업,G47414,...,4812312700100450001032421,성원아파트,경상남도 창원시 성산구 동산로 88,642778,51499,NaN,3,NaN,128.688725,35.216851
166062,MA010120220810601450,원희정횟집,NaN,I2,음식,I201,한식,I20111,횟집,I56114,...,4831010200101820003027797,NaN,경상남도 거제시 장승포로 101,656909,53319,NaN,NaN,NaN,128.729579,34.863456
166063,MA010120220806268824,미쁘다,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,4884025023104420001015321,NaN,경상남도 남해군 남해읍 화전로38번길 10-1,668803,52422,NaN,NaN,NaN,127.895789,34.835860
166064,MA010120220803813337,더꼬치다,NaN,I2,음식,I201,한식,I20110,닭/오리고기 구이/찜,I56219,...,4825011900101760009051181,NaN,경상남도 김해시 삼안로195번길 40,621909,50818,NaN,NaN,NaN,128.907655,35.245100

In [5]:
data.columns

Index(['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
       '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
       '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
       '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
       '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
       '호정보', '경도', '위도'],
      dtype='object')

In [7]:
temp = data[['상호명','상권업종대분류명','시군구명','경도','위도']]
temp

              상호명 상권업종대분류명     시군구명          경도         위도
0            일로딜로       소매  창원시 의창구  128.642214  35.234522
1          오미당꽈배기       음식      김해시  128.824132  35.171836
2            하나병원     보건의료      사천시  128.086510  35.082219
3       술마시는심플노래방       음식      통영시  128.427303  34.844565
4            남도밥상       음식      남해군  127.896689  34.842315
...           ...      ...      ...         ...        ...
166060         라온       음식      남해군  127.887291  34.837908
166061         라니       소매  창원시 성산구  128.688725  35.216851
166062      원희정횟집       음식      거제시  128.729579  34.863456
166063        미쁘다       음식      남해군  127.895789  34.835860
166064       더꼬치다       음식      김해시  128.907655  35.245100

[166065 rows x 5 columns]

In [14]:
changwon = temp[temp['시군구명'].str.contains('창원시')]
changwon

             상호명 상권업종대분류명       시군구명          경도         위도
0           일로딜로       소매    창원시 의창구  128.642214  35.234522
5            앤카키       소매  창원시 마산회원구  128.582862  35.231046
10       우리할매떡볶이       음식  창원시 마산합포구  128.558253  35.181259
12       행운로또복권방   예술·스포츠    창원시 진해구  128.706618  35.130564
22          에나면옥       음식    창원시 성산구  128.709229  35.210162
...          ...      ...        ...         ...        ...
166044      이조본가       음식    창원시 진해구  128.663718  35.151124
166045      알리바바       음식  창원시 마산회원구  128.584861  35.229450
166048    대한인테리어    과학·기술    창원시 의창구  128.647470  35.240588
166059  두루미노래연습장   예술·스포츠    창원시 의창구  128.688082  35.240860
166061        라니       소매    창원시 성산구  128.688725  35.216851

[49775 rows x 5 columns]

In [16]:
# 치킨집을 차리고싶은데 치킨집이 얼마나 많징!?
df = changwon[changwon['상호명'].str.contains('치킨')]
df

               상호명 상권업종대분류명       시군구명          경도         위도
445       호식이두마리치킨       음식    창원시 진해구  128.811609  35.102467
755     경아두마리치킨내서점       음식  창원시 마산회원구  128.521483  35.253510
975      굽네치킨마산산호점       음식  창원시 마산합포구  128.583316  35.220749
1325        치킨더홈내서       음식  창원시 마산회원구  128.501959  35.223791
1900     냠냠숯불두마리치킨       음식    창원시 진해구  128.710017  35.149194
...            ...      ...        ...         ...        ...
163747      자담치킨반월       음식  창원시 마산합포구  128.565430  35.191872
164235      자담치킨창원       음식    창원시 진해구  128.704952  35.149891
164529   처갓집양념치킨창원       음식    창원시 성산구  128.699699  35.208018
165062        교촌치킨       음식    창원시 진해구  128.656477  35.151569
165554       비비큐치킨       음식    창원시 의창구  128.598739  35.306038

[513 rows x 5 columns]

In [20]:
# 상호명에 치킨만 들어잇겟냥?!
df = changwon[changwon['상호명'].str.contains('닭')]
df

             상호명 상권업종대분류명       시군구명          경도         위도
292         또또찜닭       음식  창원시 마산회원구  128.575176  35.230118
321         국제통닭       음식    창원시 진해구  128.813520  35.088374
1382    가마치통닭메트로       음식  창원시 마산회원구  128.586115  35.223593
1743      조가네불닭발       음식    창원시 의창구  128.634770  35.257728
1778      못말리는파닭       음식  창원시 마산회원구  128.510904  35.250571
...          ...      ...        ...         ...        ...
164774    꿩대신닭곰탕       음식    창원시 성산구  128.691757  35.215635
164849     요달의찜닭       음식    창원시 진해구  128.803923  35.096037
165194     장작구이닭       음식  창원시 마산합포구  128.562242  35.175471
165284   노랑통닭반지점       음식    창원시 성산구  128.662116  35.239247
165465       아웃닭       음식    창원시 성산구  128.684483  35.220526

[460 rows x 5 columns]

In [26]:
# 둘다 같이 !!!
df = changwon[changwon['상호명'].str.contains('닭|치킨')] # '닭'|'치킨'은 오류남
df

               상호명 상권업종대분류명       시군구명          경도         위도
292           또또찜닭       음식  창원시 마산회원구  128.575176  35.230118
321           국제통닭       음식    창원시 진해구  128.813520  35.088374
445       호식이두마리치킨       음식    창원시 진해구  128.811609  35.102467
755     경아두마리치킨내서점       음식  창원시 마산회원구  128.521483  35.253510
975      굽네치킨마산산호점       음식  창원시 마산합포구  128.583316  35.220749
...            ...      ...        ...         ...        ...
165062        교촌치킨       음식    창원시 진해구  128.656477  35.151569
165194       장작구이닭       음식  창원시 마산합포구  128.562242  35.175471
165284     노랑통닭반지점       음식    창원시 성산구  128.662116  35.239247
165465         아웃닭       음식    창원시 성산구  128.684483  35.220526
165554       비비큐치킨       음식    창원시 의창구  128.598739  35.306038

[965 rows x 5 columns]