# 5장
## Series, DataFrame

In [7]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import sys
import re
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
obj = pd.Series([4,7,-5,3], index=['d','b','a','c']) 

obj4.name = 'population'  #Series 객체에 name 속성부여
obj4.index.name = 'state' #Series 색인에 name 속성부여

#DataFrame 만들기
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year' : [2000, 2001, 2002, 2001, 2002, 2003],
       'pop' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

pd.DataFrame(data, columns=['year', 'state']) #컬럼순서변경
#DataFrame 에 columns, index 직접 넣기
frame2 = pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt'],
                     index = ['one', 'two', 'three', 'four', 'five', 'six'])

# 중첩된 dictionary를 DataFrame에 넘기면, 바깥의 키는 컬럼이 되고 안쪽의 키는 로우가 된다.
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)

obj3.reindex(range(6), method='ffill')
frame2=frame.reindex(['a', 'b', 'c', 'd']) #rows 명 색인 바꾸기
states=['Texas', 'Utha', 'California'] #columns 색인 바꾸기
frame.reindex(columns=states)

obj.drop('c', inplace=True) #drop해서 없애기
data.drop('two', axis=1)

data[data['three'] > 5] #boolean 배열로 찾기
data.loc['Colorado', ['two','three']] 
data.iloc[[1,2],[3,0,1]] # row, column 둘다 선택출력.

format = lambda x: '%.2f' % x   #DataFrame은 applymap
frame.applymap(format)
frame['e'].map(format) #Series는 map

obj.sort_index(axis=1, ascending=False)  #index 정렬
frame.sort_values(by=['a','b']) #value로 정렬
obj.rank(ascending=False, method='max') #rank 매김 
obj.index.is_unique #중복색인
df.mean(axis='columns', skipna=False) # 평균값 NaN 제외
df.cumsum() #누적합
obj.value_counts() #Series에서 갯수세기

# Index.get_indexer 메서드는 여러값이 들어있는 배열에서 유일한 값의 색인 배열을 구할 수 있다.
unique_vals = obj.unique()
pd.Index(unique_vals).get_indexer(obj)

# 6장
## 파일 읽고 저장

In [ ]:
df = pd.read_csv('examples/ex1.csv') #csv파일 DataFrame으로 읽기

pd.read_csv('examples/ex2.csv', header=None, , names=['a','b','c','d','message']
            
names = ['a','b','c','d','message']
pd.read_csv('examples/ex2.csv', names=names, index_col= 'message')
            
parsed = pd.read_csv('examples/csv_mindex.csv', index_col=['key1', 'key2']) #계층적색인

result = pd.read_table('examples/ex3.txt', sep='\s+') #공백으로 분리
            
pd.read_csv('examples/ex4.csv', index_col='message', skiprows=[0,2,3]) #skiprows로 rows뛰어넘기
     
result = pd.read_csv('examples/ex5.csv', na_values=['NULL']) #누락값처리
            
sentinels = {'message': ['foo','NA'], 'something':['two']} #각각 다르게 NaN값 처리
pd.read_csv('examples/ex5.csv', na_values=sentinels)
        
pd.options.display.max_rows = 10 #일부만 가져온다
pd.read_csv('examples/ex6.csv',nrows=4) #row 4개만 가져옴
            
data.to_csv(sys.stdout, index=False, header=False) #출력 예제

# 7장
## 데이터 정제

In [ ]:
string_data.isnull() #누락데이터 찾기. boolean 값으로 알려줌
cleaned = data.dropna(how='all') #NaN을 다 포함해야만 삭제
data.dropna(axis=1, how='all') #컬럼 제거
df.dropna(thresh=2) #결측치를 제외하고 최소 2개 이상인 데이터를 가진것만 것만  
df.fillna({1:0.5, 2: 0}, inplace=True) #결측치 채우기 
df.fillna(method='ffill', limit=2) #limit 옵션을 사용해서 2개까지만 보간
data.fillna(data.mean()) #중간값으로 채우기

data.duplicated() #각 row가 중복인지 아닌지를 알려주는 Series를 반환
data.drop_duplicates() #drop_duplicates는 duplicated 배열이 False인 DataFrame을 반환
data.drop_duplicates(['k1', 'k2'], keep='last') # k1, k2 기준으로 마지막에 있는 값 반환

data.replace(-999, np.nan) #replace를 이용한 치환
data.replace({-999: np.nan, -1000: 0}) #리스트 대신 사전을 사용하는 것도 가능하다

transform = lambda x: x[:4].upper()
data.index.map(transform) #대문자로 4글자까지 바꾸기

data.rename(index={'OHIO':"INDIANA"},  #index랑 columns이름 바꾸기
           columns = {'three':'peekaboo'})

ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)

cats.codes  #4개의 categorie중 어디에 속하는지 표시
pd.value_counts(cats) #몇개인지 세줌
#중괄호 쪽의 값은 포함하지 않고 대괄호쪽의 값은 포함한다.
pd.cut(ages, [18, 26, 36, 61, 100], right=False) #중괄호 대신 대괄호쪽이 포함되지 않게 바꿀 수 있다.
#그룹 이름 지어주기
group_names = ['Youth', 'YoungAdult', 'MiddleAges', 'Senior']
pd.cut(ages, bins, labels=group_names)

data = pd.cut(data, 4, precision=2) #소숫점 둘째자리까지 
pd.value_counts(data)

cats = pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]) #직접 변위치 지정

col = data[2]
col[np.abs(col) > 3] #DataFrame의 특정 한 컬럼(data[2])에서 3을 초과하는 값을 찾는 경우
data[(np.abs(data) > 3).any(1)] #3을 초과하는 모든 row를 선택하려면 any 메소드를 사용
data[np.abs(data) > 3] = np.sign(data) * 3  #-3이나 3을 초과하는 값을 -3 또는 3으로 지정, np.sign(data)는 부호에 따라 1이나 -1을 반환
data.describe()
np.sign(data).head()#양수, 음수 구분

df = pd.DataFrame(np.arange(5*4).reshape((5,4)))
sampler = np.random.permutation(5) #임의 순서로 재배치
df.take(sampler) #take 함수를 사용

choices = pd.Series([5, 7, -1, 6, 4])
draws = choices.sample(n=10, replace=True) #반복선택을 허용하며, 표본을 치환을 통해 생성해내려면 replace=True 옵션 사용

df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})
pd.get_dummies(df['key'], prefix='key') #원핫인코딩, 앞에 key_a 처럼 표시

#통계 내기
np.random.seed(12345)
values = np.random.rand(10)
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.cut(values, bins)
pd.get_dummies(pd.cut(values, bins))

val = 'a,b,   guido'
val.split(',')  #,로 구분된 문자열은 split 메소드를 이용해 분리
pieces = [x.strip() for x in val.split(',')] #공백제거

text = "foo bar\t baz   \tqux" #여러가지 공백문자(탭, 스페이스, 개행문자)가 포함된 문자열
regex = re.compile('\s+') #먼저 컴파일
regex.split(text)         #정규표현식 객체 재사용

r = re.compile("[ab]")
print(r.search("pizza")) #a가 하나라도 일치
print(r.match("pizza"))
print(r.match("abcd")) #완전히 일치

print(regex.sub('REDACTED', text)) #regex에 등록된 패턴을 REACTED로 바꾸기

data.str.contains('gmail') #gmail이 포함된거 있는지 없는지 boolean으로 알려줌
data.str.findall(pattern, flags=re.IGNORECASE)

data.str[:5]  #문자열을 잘라내기

#### match와 search는 findall 메서드와 관련이 있다.
#### findall : 문자열에서 일치하는 모든 부분 문자열을 찾아준다. 
#### search : 패턴과 일치하는 첫 번째 존재를 반환한다. 
#### match : 문자열의 시작부분에서 일치하는 것만 찾아준다 
#### sub : 찾은 패턴을 주어진 문자열로 치환하여 새로운 문자열을 반환

# 8장
## merge, join ..

In [ ]:
#계층적 색인
data = pd.Series(np.random.randn(9),
                index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                      [1, 2, 3, 1, 3, 1, 2, 2, 3]]) 

data.loc[['b', 'd']] #부분적 색인으로 접근
data['b':'c']

data.unstack() #로우를 컬럼으로 
data.unstack().stack()

frame.index.names = ['key1', 'key2'] #계층적 색인에 이름을 부여하고 출력하기
frame.columns.names = ['state', 'color']
frame.swaplevel('key1', 'key2') #계층의 순서 바꿈
frame.sort_index(level=0) #인덱스 정렬
frame.swaplevel(0,1).sort_index(level=1) #같이 사용 가능
frame.sum(level='color', axis=1) #계층별 통계

frame2 = frame.set_index(['c', 'd']) #set_index함수는 하나 이상의 컬럼을 색인으로 하는 DataFrame을 생성한다.
frame.set_index(['c','d'], drop=False) #컬럼을 명시적으로 남기지 않으면 DataFrame에서 사라진다.
frame2.reset_index() #원래대로

#### 머지: 컬럼값이 공통되는게 있을때 2개를 합침. 왼쪽 데이터프레임 기4준으로 합칠꺼냐, 오른쪽 ..
#### 조인: 다른 컬럼값을 붙일때
#### combine first: 없는 거
#### melt: 밑으로 쭉 늘어뜨려서 녹여줌.
#### pivot: 원하는 테이블로 재구성. 머지랑 많이 쓰임

#### p1.pivot_table(index, columns, values, aggfunc)  
####      index : index 색인으로 사용될 컬럼  
####      columns : column 색인으로 사용될 컬럼  
####      values : value에 채우고자 하는 컬럼
####     aggfund : 데이터 집계함수

#### pandas에는 pivot과 pivot_table 두가지를 제공하는데, 
#### 차이는 pivot은 중복된 index와 column을 처리하지 못하는데, pivot_table은 처리할 수 있다. - 즉 Grouping을 할 수 있다.

In [ ]:
pd.merge(df1, df2) #어떤 컬럼을 병합할지 명시하지 않으면, merge함수는 중복된 컬럼이름을 키로 사용
pd.merge(df1, df2, on='key') #명시적으로 지정해주는 것이 좋다.
pd.merge(df3, df4, left_on='lkey', right_on='rkey', how='outer') # 만약 두 객체에 중복된 컬럼이 하나도 없다면 따로 지정해주면 된다.
pd.merge(df1, df2, how='right') #오른쪽 테이블에 존재하는 모든 키 조합을 사용한다.

pd.merge(df1, df2, on='key', how='left') #다대다의 경우, 두 로우의 데카르트곱을 반환, 왼쪽 b 3개, 오른쪽 b 2개 -> 6개의 b 
pd.merge(df1, df2, how='inner') #inner는 양쪽 테이블 모두에 존재하는 키 조합을 사용
pd.merge(left, right, on=['key1', 'key2'], how='outer') #key1이랑 key2를 같이 비교해서 합집합
pd.merge(left, right, on='key1', suffixes=('_left', '_right')) #컬럼 이름이 겹칠 경우 _left, _right 로 표기해주는 suffixes

pd.merge(left1, right1, left_on='key', right_index=True) #'오른쪽의 index를 병합키로.
pd.merge(left2, right2, how='outer', left_index=True, right_index=True)

#색인으로 병합할때 DataFrame의 join메소드를 사용하면 편리하다. 
left2.join(right2, how='outer')
left1.join(right1, on='key')
left2.join([right2, another]) #concat이 더 편함

pd.concat([s1, s2, s3])
pd.concat([s1, s2, s3], axis=1) #axis=1을 넘기면 결과는 Series가 아니라 DataFrame이 된다.
pd.concat([s1, s4], axis=1, join='inner') #교집합으로
pd.concat([s1, s4], axis=1).reindex(['a', 'c', 'b', 'e']) #index 재조정
#Series 붙이고 식별하기편하도록 계층적 색인 넣어줌
result = pd.concat([s1, s2, s3], keys=['one', 'two', 'three']) #계층적 색인 사용 (s1, s2, s3 구별할수 있게 색인 부여)
pd.concat({'level1':df1, 'level2': df2}, axis=1) #리스트 대신 객체의 사전을 넘기면 사전의 키가 keys옵션으로 사용된다. 
pd.concat([df1, df2], ignore_index=True) #인덱스 무시하고 그냥 이어붙임

#일부나 전체가 겹치면?
np.where(pd.isnull(a), b, a) #a를 봐서 null 이면 b로 가고 값이 있으면 a로.
a.combine_first(b)

#1. stack - 데이터의 컬럼을 로우로 피벗(또는 회전) 시킨다.
#2. unstack - 로우를 컬럼으로 피벗 시킨다. 기본적으로 가장 안쪽에 있는 레벨부터 끄집어낸다. 
result.unstack('state')
data2.unstack().stack(dropna=False) #stack에선 dropna가 default 값
df.unstack('state').stack('side') #stack을 호출할때 쌓을 축의 이름을 지정할 수있다.


#p1.pivot(index=None, columns=None, values=None)
#index : index 색인으로 사용될 컬럼
#columns : column 색인으로 사용될 컬럼
#values : value에 채우고자 하는 컬럼
#처음 두인자는 로우와 컬럼 색인으로 사용될 컬럼이름이고 마지막 인자는 DataFrame에 채워넣을 값을 담고있는 컬럼 이름이다.
pivoted = ldata.pivot('date', 'item', 'value')
reshaped = melted.pivot('key', 'variable', 'value')
reshaped.reset_index() #pivot은 로우를 컬럼색인으로 사용하므로 reset_index를 이용해서 데이터를 다시 컬럼으로 되돌린디.

melted = pd.melt(df, ['key']) #melt를 사용할때에는 반드시 어떤 컬럼을 구분자로 사용할 것인지 지정해야 한다.
pd.melt(df, id_vars=['key'], value_vars=['A','B']) #데이터값으로 사용할 컬럼들의 집합을 지정할 수 있다.

### 어느 회사의 전반기(1월 ~ 6월) 실적을 나타내는 데이터프레임과 후반기(7월 ~ 12월) 실적을 나타내는 데이터프레임을 만든 뒤 합친다. 실적 정보는 “매출”, “비용”, “이익” 으로 이루어진다. (이익 = 매출 - 비용). 또한 1년간의 총 실적을 마지막 행으로 덧붙인다.

In [9]:
np.random.seed(0)
df1=pd.DataFrame(np.random.randint(1,15,size=(2,6)),columns=[i for i in range(1,7)],index=['매출','비용'])
df2=pd.DataFrame(np.random.randint(1,20,size=(2,6)),columns=[i for i in range(7,13)],index=['매출','비용'])
df3=pd.concat([df1,df2],axis=1)
df3.loc['이익']=df3.apply(lambda x:int(x.loc['매출'])-int(x.loc['비용']))
df3['총실적']=[sum(df3.loc['매출']),sum(df3.loc['비용']),sum(df3.loc['이익'])]
df3

     1   2  3  4   5  6   7   8   9  10  11  12  총실적
매출  13   6  1  4  12  4   7  13   2   7   8  15   92
비용   8  10  4  6   3  5  18   6  14   9  10  17  110
이익   5  -4 -3 -2   9 -1 -11   7 -12  -2  -2  -2  -18

# 9장
## 시각화

In [ ]:
plt.plot(data, 'k--', label='Default') #기본

#분할해서 그리기
fig = plt.figure()
ax1 = fig.add_subplot(2,2,1)
ax2 = fig.add_subplot(2,2,2)
ax3 = fig.add_subplot(2,2,3)
plt.plot(np.random.randn(50).cumsum(), 'k--') #matplotlib는 가장 최근의 figure와 그 subplot을 그린다.
#_ = ax1.hist(np.random.randn(100), bins=20, color='k', alpha=0.3) #bin:막대의 갯수, alpha:투명도(0이면 완전 투명, 1이면 완전 불투명)
ax1.hist(np.random.randn(100), bins=20, color='k', alpha=0.5) #bin:막대의 갯수, alpha:투명도(0이면 완전 투명, 1이면 완전 불투명)
ax2.scatter(np.arange(30), np.arange(30) + 3 * np.random.randn(30))

#원형 그래프
ratio = [34, 32, 16, 18]
labels = ['Apple', 'Banaana', 'Melon', 'Grapes']
plt.pie(ratio, labels=labels, autopct='%.1f%%',
       startangle=260, counterclock=False)
plt.show()

#수직바
df.plot.bar()
#수평바
df.plot.barh(stacked=True, alpha=1.0)